#!/bin/sh
# Moombox Docker entrypoint.
#
# Seeds /data/config.toml on first run, then execs the moombox binary so
# it receives signals directly (docker stop → SIGTERM → graceful shutdown).
#
# The seed sets network_access = "lan" — inside a container the dashboard
# is only reachable through the published port, and requests arriving over
# Docker's bridge network are never loopback from the container's point of
# view, so the binary's "localhost" default would make the dashboard
# unreachable (and the first-run web setup wizard, whose completion
# endpoint is loopback-only, cannot be used either). Docker's port
# publishing is the exposure control: publish "127.0.0.1:774:774" to keep
# the dashboard host-only.
#
# An existing config.toml is never modified — change settings there or via
# the dashboard's Settings page as usual.
set -eu

CONFIG_PATH="${MOOMBOX_CONFIG:-/data/config.toml}"

if [ ! -f "$CONFIG_PATH" ]; then
    echo "[moombox-entrypoint] no config found — seeding $CONFIG_PATH (network_access = \"lan\")"
    cat > "$CONFIG_PATH" <<'EOF'
# Generated by the Moombox Docker entrypoint on first run.
# Only settings that differ from the built-in defaults are listed;
# Moombox fills in the remaining sections with defaults on startup.
# Full reference:
# https://github.com/vampiricwulf/Moombox/blob/main/config.example.toml

[network]
# "lan" is the Docker default — the container is only reachable through
# published ports, and those arrive over the bridge network (not
# loopback). Restrict exposure via the port publish (e.g.
# "127.0.0.1:774:774") or set "external" + a dashboard password to allow
# non-private clients. For internet exposure, read "Remote access" in the
# README first (trusted_proxies, TLS, and the Tailscale/VPN option).
network_access = "lan"
# Must match the container's EXPOSEd port and the docker-compose
# healthcheck — change all three together.
port = 774
# Behind a TLS-terminating reverse proxy (nginx, Caddy, Traefik)?
# See trust_forwarded_proto in config.example.toml.

[paths]
database_path = "/data/moombox.db"
log_file_path = "/data/moombox.log"
output_directory = "/data/output"
staging_directory = "/data/staging"

[cookies]
# Netscape cookie file for members-only content. Put it at
# ./data/cookies.txt on the host — the /data volume already exposes it.
# Do NOT bind-mount the file on its own: Moombox rewrites it (temp file +
# rename) to keep the rotated YouTube session alive, and a rename cannot
# replace a single-file bind mount. See docker-compose.yml.
cookie_file = "/data/cookies.txt"
# Alternative to exporting cookies.txt by hand: bind-mount a Firefox
# profile directory (the one holding prefs.js and cookies.sqlite, not its
# parent) at /data/browser-profile.
# browser_profile_dir needs no entry — it defaults to ./browser-profile,
# which resolves to /data/browser-profile here.
# This image ships no browser, so Moombox reads the profile directly
# instead of launching one — and never writes into it. Copy the profile
# with Firefox closed, and keep cookies.sqlite-wal next to
# cookies.sqlite; recent cookies live in that sidecar and a copy without
# it reads as empty.
#
# auto_enabled is left OFF here on purpose, and should stay off. All it
# does is start a slow headless-browser refresh timer and allow one
# automatic browser attempt when auth fails — and there is no browser in
# this image to run either. It does NOT gate the profile import.
#
# FIRST BOOT IS AUTOMATIC. If there is no cookies.txt yet, Moombox
# imports the mounted profile once, shortly after start, on its own —
# there is nothing on disk to lose, so mount a profile and start.
#
# After that the profile is deliberately NOT re-read on a timer: nothing
# inside the container changes it, so a timer would re-read identical
# bytes over credentials that may still be working. YOU are what changes
# it, so you trigger the read: refresh the profile on the host (Firefox
# closed, .sqlite-wal included), then press "Refresh cookies from browser
# profile" on the dashboard's Settings page — or shift+click the header's
# "Refresh cookies", or press R F in the TUI. All three import straight
# from the profile with no browser, whatever auto_enabled says and
# whatever cookies.txt already holds. On a phone or tablet use the
# Settings button: shift+click needs a keyboard.
#
# NO PROFILE, OR THE PROFILE ITSELF IS STALE? Paste it instead. The
# dashboard's Settings -> Cookies panel accepts a Netscape cookies.txt
# by paste or upload: it MERGES into the file above (a YouTube-only
# export leaves Twitch alone), reloads it immediately and reports
# whether it authenticates. No browser, no shell, no access to the
# data volume -- which makes it the re-auth path for this image, and
# the only one that works from a phone. Export from a private window
# and close it: browsing on in the source profile invalidates it.
#
# The in-process refresh that keeps the imported YouTube session alive
# between imports runs regardless; it needs only cookie_file above.
#
# Shown for reference and deliberately NOT enabled:
# auto_enabled = true

[updates]
# The in-app updater would swap the binary INSIDE the container, and
# that is silently reverted whenever the container is recreated from
# its image. Update by pulling a new image instead:
#   docker compose pull && docker compose up -d
# Set to true if you still want new-release notifications in the
# dashboard (the manual "Check for updates" button works either way).
auto_check_updates = false
EOF
fi

# `moombox add <url>` is a positional subcommand (must stay argv[1]) —
# pass it through untouched; it resolves config from the cwd (/data).
if [ "${1:-}" = "add" ]; then
    exec moombox "$@"
fi

exec moombox -config "$CONFIG_PATH" "$@"
