#!/bin/sh
# Moombox Docker entrypoint.
#
# Seeds /data/config.toml on first run, then execs the moombox binary so
# it receives signals directly (docker stop → SIGTERM → graceful shutdown).
#
# The seed sets network_access = "lan" — inside a container the dashboard
# is only reachable through the published port, and requests arriving over
# Docker's bridge network are never loopback from the container's point of
# view, so the binary's "localhost" default would make the dashboard
# unreachable (and the first-run web setup wizard, whose completion
# endpoint is loopback-only, cannot be used either). Docker's port
# publishing is the exposure control: publish "127.0.0.1:774:774" to keep
# the dashboard host-only.
#
# An existing config.toml is never modified — change settings there or via
# the dashboard's Settings page as usual.
set -eu

CONFIG_PATH="${MOOMBOX_CONFIG:-/data/config.toml}"

if [ ! -f "$CONFIG_PATH" ]; then
    echo "[moombox-entrypoint] no config found — seeding $CONFIG_PATH (network_access = \"lan\")"
    cat > "$CONFIG_PATH" <<'EOF'
# Generated by the Moombox Docker entrypoint on first run.
# Only settings that differ from the built-in defaults are listed;
# Moombox fills in the remaining sections with defaults on startup.
# Full reference:
# https://github.com/vampiricwulf/Moombox/blob/main/config.example.toml

[network]
# "lan" is the Docker default — the container is only reachable through
# published ports, and those arrive over the bridge network (not
# loopback). Restrict exposure via the port publish (e.g.
# "127.0.0.1:774:774") or set "external" + a dashboard password to allow
# non-private clients. For internet exposure, read "Remote access" in the
# README first (trusted_proxies, TLS, and the Tailscale/VPN option).
network_access = "lan"
# Must match the container's EXPOSEd port and the docker-compose
# healthcheck — change all three together.
port = 774
# Behind a TLS-terminating reverse proxy (nginx, Caddy, Traefik)?
# See trust_forwarded_proto in config.example.toml.

[paths]
database_path = "/data/moombox.db"
log_file_path = "/data/moombox.log"
output_directory = "/data/output"
staging_directory = "/data/staging"

[cookies]
# Netscape cookie file for members-only content. Put it at
# ./data/cookies.txt on the host — the /data volume already exposes it.
# Do NOT bind-mount the file on its own: Moombox rewrites it (temp file +
# rename) to keep the rotated YouTube session alive, and a rename cannot
# replace a single-file bind mount. See docker-compose.yml.
cookie_file = "/data/cookies.txt"

[updates]
# The in-app updater would swap the binary INSIDE the container, and
# that is silently reverted whenever the container is recreated from
# its image. Update by pulling a new image instead:
#   docker compose pull && docker compose up -d
# Set to true if you still want new-release notifications in the
# dashboard (the manual "Check for updates" button works either way).
auto_check_updates = false
EOF
fi

# `moombox add <url>` is a positional subcommand (must stay argv[1]) —
# pass it through untouched; it resolves config from the cwd (/data).
if [ "${1:-}" = "add" ]; then
    exec moombox "$@"
fi

exec moombox -config "$CONFIG_PATH" "$@"
