#!/bin/sh
# Moombox Docker entrypoint.
#
# Seeds /data/config.toml on first run, then execs the moombox binary so
# it receives signals directly (docker stop → SIGTERM → graceful shutdown).
#
# The seed sets network_access = "lan" — inside a container the dashboard
# is only reachable through the published port, and requests arriving over
# Docker's bridge network are never loopback from the container's point of
# view, so the binary's "localhost" default would make the dashboard
# unreachable (and the first-run web setup wizard, whose completion
# endpoint is loopback-only, cannot be used either). Docker's port
# publishing is the exposure control: publish "127.0.0.1:774:774" to keep
# the dashboard host-only.
#
# An existing config.toml is never modified — change settings there or via
# the dashboard's Settings page as usual.
set -eu

CONFIG_PATH="${MOOMBOX_CONFIG:-/data/config.toml}"

if [ ! -f "$CONFIG_PATH" ]; then
    echo "[moombox-entrypoint] no config found — seeding $CONFIG_PATH (network_access = \"lan\")"
    cat > "$CONFIG_PATH" <<'EOF'
# Generated by the Moombox Docker entrypoint on first run.
# Only settings that differ from the built-in defaults are listed;
# Moombox fills in the remaining sections with defaults on startup.
# Full reference:
# https://github.com/vampiricwulf/Moombox/blob/main/config.example.toml

[network]
# "lan" is the Docker default — the container is only reachable through
# published ports, and those arrive over the bridge network (not
# loopback). Restrict exposure via the port publish (e.g.
# "127.0.0.1:774:774") or set "external" + a dashboard password to allow
# non-private clients.
network_access = "lan"

[paths]
database_path = "/data/moombox.db"
log_file_path = "/data/moombox.log"
output_directory = "/data/output"
staging_directory = "/data/staging"
EOF
fi

# `moombox add <url>` is a positional subcommand (must stay argv[1]) —
# pass it through untouched; it resolves config from the cwd (/data).
if [ "${1:-}" = "add" ]; then
    exec moombox "$@"
fi

exec moombox -config "$CONFIG_PATH" "$@"
