// Rendering pins for web/public/app.js — see helpers/app-dom.mjs.
//
// app.js is about to be split into controllers (Arc I, tasks 6-10). Those are
// pure moves, so the proof they are correct is that the RENDERED OUTPUT does
// not change: every test below reads what the app draws, never how it draws
// it, and the big ones compare against a snapshot in
// fixtures/app-job-items.json byte for byte.
//
// Like player.test.mjs, this suite needs jsdom. `node --test web/tests/*.test.mjs`
// must stay green without it, so the import is probed first and every test is
// skipped (not failed) when jsdom is absent.
import { test, after } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseFilterQuery } from "../public/modules/filter-parser.js";

let jsdomMissing = null;
try {
  await import("jsdom");
} catch (e) {
  // ONLY an absent module is a skip. Any other import failure — a half-written
  // install, a syntax error inside jsdom — must fail loudly instead of turning
  // every DOM test into a green "skipped" line nobody reads.
  if (e.code !== "ERR_MODULE_NOT_FOUND") throw e;
  jsdomMissing = `jsdom not installed — run \`npm ci\` in web/tests (${e.code})`;
}
// Imported only when jsdom is present, so a real fault in the helper is a
// failure, not a silent skip. The fixture INPUTS live beside the harness
// because they are written in terms of its frozen clock.
const harness = jsdomMissing ? null : await import("./helpers/app-dom.mjs");
const inputs = jsdomMissing ? null : await import("./fixtures/app-render-inputs.mjs");
const skip = jsdomMissing || false;

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SNAPSHOT = jsdomMissing
  ? null
  : JSON.parse(fs.readFileSync(path.join(HERE, "fixtures", "app-job-items.json"), "utf8"));

after(() => harness?.teardownAll());

// ── 1. Job cards, one per status ────────────────────────────────────────────

test("renderJobItem draws every job status exactly as the snapshot", { skip }, async () => {
  const h = await harness.makeApp();

  // Every status the dashboard can show, so a controller extraction that
  // drops a branch (a badge, an overflow item, an indicator) fails here.
  assert.deepEqual(
    Object.keys(inputs.JOBS),
    ["Upcoming", "Live", "Downloading", "Muxing", "Finished", "Error", "Cancelled", "COOKIES?", "Queued"],
  );

  for (const [status, job] of Object.entries(inputs.JOBS)) {
    assert.equal(h.app.renderJobItem(job), SNAPSHOT.jobItems[status], `renderJobItem(${status})`);
  }

  // A couple of load-bearing details called out explicitly, so a snapshot
  // regenerated by mistake still has to explain itself.
  assert.match(SNAPSHOT.jobItems.Upcoming, /Last check: 5m ago/);
  assert.match(SNAPSHOT.jobItems["COOKIES?"], /Not a member — needs member account/);
  assert.match(SNAPSHOT.jobItems["COOKIES?"], />Auth Required</);
  assert.match(SNAPSHOT.jobItems.Downloading, /V:1234 A:1234 C:5678/);
  assert.match(SNAPSHOT.jobItems.Live, /TW<\/sl-tag>/);
  assert.ok(!SNAPSHOT.jobItems.Cancelled.includes("<script"));
});

// ── 2. Files + History tabs ─────────────────────────────────────────────────

test("renderOrphanedFiles and renderOrphanedHistory draw the snapshot rows", { skip }, async () => {
  const h = await harness.makeApp();

  h.app.renderOrphanedFiles(inputs.FILES);
  const fileRows = [...h.el("files-table").querySelectorAll(".files-row")].map((r) => r.outerHTML);
  assert.deepEqual(fileRows, SNAPSHOT.orphanedFiles);
  // Staging sorts ahead of output regardless of input order.
  assert.match(fileRows[0], /files-type-badge staging/);
  assert.equal(h.el("files-empty").style.display, "none");
  assert.equal(h.el("files-table-wrapper").style.display, "");
  assert.equal(h.el("files-delete-all-btn").disabled, false);

  h.app.renderOrphanedHistory(inputs.HISTORY);
  const historyRows = [...h.el("history-table").querySelectorAll(".history-row")].map((r) => r.outerHTML);
  assert.deepEqual(historyRows, SNAPSHOT.orphanedHistory);
  assert.equal(h.el("history-empty").style.display, "none");
  assert.equal(h.el("history-delete-all-btn").disabled, false);

  // The empty and error arms differ only in the message; both hide the table.
  h.app.renderOrphanedFiles([]);
  assert.equal(h.el("files-empty").style.display, "");
  assert.equal(h.el("files-table-wrapper").style.display, "none");
  assert.equal(h.el("files-empty").querySelector("p").textContent, "No orphaned files found.");
  h.app.renderOrphanedFiles(null);
  assert.equal(h.el("files-empty").querySelector("p").textContent,
    "Failed to load orphaned files. Try refreshing.");
  h.app.renderOrphanedHistory(null);
  assert.equal(h.el("history-empty").querySelector("p").textContent,
    "Failed to load orphaned history. Try refreshing.");
});

// ── 3. Version indicator ────────────────────────────────────────────────────

test("updateVersionIndicator flips between the plain version and the update badge", { skip }, async () => {
  // The version arrives from GET /api/status, the same way the real app gets it.
  const h = await harness.makeApp({
    initialState: { status: { version: "2.8.7", updateAvailable: { version: "9.9.9", tagName: "v9.9.9" } } },
  });
  const el = h.el("version-indicator");

  assert.equal(h.app._updateAvailable.version, "9.9.9");
  assert.equal(el.textContent, "v2.8.7 ⬆");
  assert.equal(el.className, "version-indicator has-update");
  assert.equal(el.title, "Update available: v9.9.9");
  assert.equal(el.style.cursor, "pointer");
  assert.equal(el.style.display, "");

  h.app._updateAvailable = null;
  h.app.updateVersionIndicator();
  assert.equal(el.textContent, "v2.8.7");
  assert.equal(el.className, "version-indicator");
  assert.equal(el.title, "Moombox v2.8.7 — click to open the GitHub page");
  assert.equal(el.style.cursor, "");

  // No version at all (a status fetch that never landed) hides it entirely.
  h.app._version = null;
  h.app.updateVersionIndicator();
  assert.equal(el.style.display, "none");
});

// ── 4. Log panel ────────────────────────────────────────────────────────────

test("the WARN filter renders only ERROR and WARN lines, with the count suffix", { skip }, async () => {
  const h = await harness.makeApp();
  const viewer = h.el("logs-viewer");

  // addLog takes the raw log LINE (the level is parsed out of the text).
  for (const line of [
    "2026-09-05 12:00:00 WARN cookies are close to expiry",
    "2026-09-05 12:00:01 WARN twitch token refreshed late",
    "2026-09-05 12:00:02 WARN feed poll returned 429",
    "2026-09-05 12:00:03 DEBUG segment 1234 written",
    "2026-09-05 12:00:04 ERROR mux failed",
  ]) h.app.addLog(line);

  // Unfiltered, the fast append path draws one line per entry.
  assert.equal(viewer.children.length, 5);
  assert.equal(h.el("log-count").textContent, "5 log entries");

  // The real gesture: click the WARN filter button.
  h.el("logs-container").ownerDocument.querySelector('.log-filter[data-level="WARN"]').click();

  assert.equal(h.app.logPanel.logFilter, "WARN");
  assert.equal(viewer.children.length, 4, "DEBUG is below the WARN threshold");
  assert.equal(h.el("log-count").textContent, "4 log entries (WARN+)");
  assert.deepEqual([...viewer.children].map((d) => d.className),
    ["log-line log-warn", "log-line log-warn", "log-line log-warn", "log-line log-error"]);
  assert.equal(viewer.children[3].textContent, "2026-09-05 12:00:04 ERROR mux failed");
  assert.ok(![...viewer.children].some((d) => d.textContent.includes("DEBUG")));

  // Clear empties both the buffer and the view.
  h.el("clear-logs-btn").click();
  assert.deepEqual(h.app.logPanel.logs, []);
  assert.equal(viewer.children.length, 0);
});

// ── 5. Unified filter bar ───────────────────────────────────────────────────

test("typing a filter query turns structured terms into labelled chips", { skip }, async () => {
  const h = await harness.makeApp();
  const container = h.el("tasks-filter");
  const input = container.querySelector(".unified-filter-input");
  const chips = container.querySelector(".unified-filter-chips");

  input.value = "status:live -platform:twitch keyword";
  input.dispatchEvent(new h.window.KeyboardEvent("keydown", { key: "Enter", bubbles: true, cancelable: true }));

  // The tokens the app now holds are exactly what the parser produces.
  const parsed = parseFilterQuery("status:live -platform:twitch keyword");
  assert.deepEqual(
    h.app.filterBar.tasksFilterTokens.map((t) => ({ type: t.type, value: t.value, negate: !!t.negate })),
    parsed.map((t) => ({ type: t.type, value: t.value, negate: !!t.negate })),
  );

  // Structured terms become chips labelled by _filterTokenLabel (negation
  // keeps its leading "-"); free text stays in the input, never chipped.
  assert.deepEqual([...chips.children].map((c) => c.tagName), ["SL-TAG", "SL-TAG"]);
  assert.deepEqual([...chips.children].map((c) => c.textContent), ["live", "-Twitch"]);
  assert.equal(input.value, "keyword");
  assert.equal(h.el("tasks-filter").querySelector(".unified-filter-clear").style.display, "");

  // The labels come from _filterTokenLabel, so pin it directly too.
  assert.equal(h.app.filterBar._filterTokenLabel({ type: "status", value: "issues" }), "Issues");
  assert.equal(h.app.filterBar._filterTokenLabel({ type: "platform", value: "youtube" }), "YouTube");
  assert.equal(h.app.filterBar._filterTokenLabel({ type: "channel", value: "Chan" }), "Chan");
  assert.equal(h.app.filterBar._filterTokenLabel({ type: "text", value: "raw" }), "raw");
});

// ── 6. Toasts ───────────────────────────────────────────────────────────────

test("showToast appends an sl-alert with the variant's icon", { skip }, async () => {
  const h = await harness.makeApp();
  assert.equal(h.toasts().length, 0);

  h.app.showToast("x", "primary");
  h.app.showToast("saved", "success");

  const toasts = h.toasts();
  assert.equal(toasts.length, 2);
  // Shoelace is not loaded, so the assertion is structural: the right element
  // name, the right text, and .toast() actually called on it.
  assert.equal(toasts[0].tagName, "SL-ALERT");
  assert.equal(toasts[0].variant, "primary");
  assert.equal(toasts[0].textContent, "x");
  assert.equal(toasts[0].querySelector("sl-icon").name, "info-circle");
  assert.deepEqual(toasts[0]._calls, ["toast"]);
  assert.equal(toasts[1].querySelector("sl-icon").name, "check2-circle");
  assert.equal(toasts[1].textContent, "saved");
});
