"""Generate release notes for GitHub Releases using Claude Opus 4.6.

Called by .github/workflows/release.yml during tag-triggered builds.
Falls back to a simple download link if ANTHROPIC_API_KEY is not set
or if the API call fails. Supports both API keys (x-api-key) and
OAuth tokens (Authorization: Bearer).
"""

import argparse
import json
import os
import subprocess
import sys
import urllib.request
import urllib.error


def get_commits(tag: str) -> str:
    """Get commit log since the previous tag."""
    try:
        prev_tag = subprocess.check_output(
            ["git", "describe", "--tags", "--abbrev=0", f"{tag}^"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except subprocess.CalledProcessError:
        # No previous tag — use first commit
        prev_tag = subprocess.check_output(
            ["git", "rev-list", "--max-parents=0", "HEAD"],
            text=True,
        ).strip()

    try:
        commits = subprocess.check_output(
            ["git", "log", "--pretty=format:- %s (%h)", f"{prev_tag}..{tag}"],
            text=True,
        ).strip()
    except subprocess.CalledProcessError:
        commits = subprocess.check_output(
            ["git", "log", "--pretty=format:- %s (%h)", "-20"],
            text=True,
        ).strip()

    return commits


def call_claude(commits: str, tag: str) -> str | None:
    """Call Claude API to generate release notes. Returns None on failure."""
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        return None

    prompt = (
        f"You are writing release notes for Moombox, a YouTube live stream archiver. "
        f"Given the following git commits for version {tag}, write concise, user-friendly "
        f"release notes. Group changes into sections like Features, Improvements, Bug Fixes, "
        f"and Internal as appropriate. Skip any section that has no entries. Focus on what "
        f"matters to users. Do not include a heading — start directly with the sections. "
        f"Use markdown formatting.\n\nCommits:\n{commits}"
    )

    body = json.dumps({
        "model": "claude-opus-4-6",
        "max_tokens": 1024,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()

    headers = {
        "Content-Type": "application/json",
        "anthropic-version": "2023-06-01",
    }
    # OAuth tokens start with specific prefixes; API keys start with "sk-ant-"
    if api_key.startswith("sk-ant-"):
        headers["x-api-key"] = api_key
    else:
        headers["Authorization"] = f"Bearer {api_key}"

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers=headers,
    )

    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read())
            if data.get("content") and len(data["content"]) > 0:
                return data["content"][0]["text"]
    except (urllib.error.URLError, json.JSONDecodeError, KeyError, IndexError) as e:
        print(f"Claude API call failed: {e}", file=sys.stderr)

    return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tag", required=True, help="Git tag (e.g. v1.4.0)")
    parser.add_argument("--repo", required=True, help="GitHub repo (owner/name)")
    parser.add_argument("--output", required=True, help="Output markdown file")
    args = parser.parse_args()

    download_url = (
        f"https://github.com/{args.repo}/releases/download/{args.tag}/Moombox.exe"
    )
    download_link = f"[**`\U0001F4E6 Download Moombox.exe for Windows`**]({download_url})"

    commits = get_commits(args.tag)
    notes = call_claude(commits, args.tag)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(download_link + "\n\n")
        if notes:
            f.write("---\n\n")
            f.write(notes.strip() + "\n\n")
            f.write("---\n")
            f.write("*Release notes generated by Claude Opus 4.6*\n")

    print(f"Release notes written to {args.output}")


if __name__ == "__main__":
    main()
