//go:build windows && amd64

package embed

import _ "embed"

// EmbeddedNode holds the gzipped Windows x64 node.exe binary embedded
// into Moombox.exe. Generated by tools/fetch-node. ~33 MB at v22.22.2.
//
//go:embed node-windows-amd64.gz
var EmbeddedNode []byte
