// Package embed exposes the BotGuard sidecar's binary blobs via go:embed
// so the sidecar manager can extract them on first launch.
//
// Files in this directory:
//   - node.exe.gz       Pinned Node.js Windows x64 binary, gzipped.
//                       Generated by `go run ./tools/fetch-node`.
//   - sidecar.tar.gz    Production node_modules + src/ + package*.json
//                       tarball. Generated by `bgutil-sidecar/build.mjs`.
//   - version.txt       Cache-invalidation key. Format:
//                       "node@vX.Y.Z sha256@<sha>". Re-extraction is
//                       triggered when the on-disk version.txt differs
//                       from this committed copy.
//
// Both .gz blobs are gitignored (built per-CI/per-dev) and version.txt
// is committed.
package embed

// The blank import below is what enables the //go:embed directives. Even
// though our package is also named "embed", the import path is "embed"
// from the standard library; the underscore prevents binding a local name
// (which would collide with our own package identity).
import _ "embed"

// NodeExeGz holds the gzipped Windows x64 node.exe binary embedded into
// moombox.exe. Generated by tools/fetch-node and regenerated on every
// build. ~33 MB at v22.22.2.
//
//go:embed node.exe.gz
var NodeExeGz []byte

// SidecarTarGz holds the gzipped tarball of the bgutil-sidecar/ folder
// (package.json, package-lock.json, src/, and production node_modules/).
// Generated by bgutil-sidecar/build.mjs. ~3.5 MB.
//
//go:embed sidecar.tar.gz
var SidecarTarGz []byte

// Version is the cache-invalidation stamp baked into moombox.exe at build
// time. The sidecar manager compares this against the on-disk version.txt
// in the cache dir; mismatch triggers re-extraction. Format:
// "node@vX.Y.Z sha256@<sha>".
//
//go:embed version.txt
var Version string
