// Package embed exposes the BotGuard sidecar's binary blobs via go:embed
// so the sidecar manager can extract them on first launch.
//
// Files in this directory:
//   - node-windows-amd64.gz   Pinned Node.js Windows x64 binary, gzipped.
//   - node-linux-amd64.gz     Pinned Node.js Linux x64 binary, gzipped.
//   - node-linux-arm64.gz     Pinned Node.js Linux arm64 binary, gzipped.
//     All three generated by `go run ./tools/fetch-node`.
//     Each platform's build embeds only its own blob
//     via per-platform _<goos>_<goarch>.go files.
//   - sidecar.tar.gz          Production node_modules + src/ + package*.json
//     tarball. Generated by `bgutil-sidecar/build.mjs`.
//     Platform-agnostic JS, embedded once here.
//   - version.txt             Cache-invalidation key. Format:
//     "node@vX.Y.Z windows-amd64@<sha> linux-amd64@<sha>
//     linux-arm64@<sha>". Re-extraction is triggered
//     when the on-disk version.txt differs.
//
// All .gz blobs are gitignored (built per-CI/per-dev) and version.txt
// is committed.
//
// EmbeddedNode is declared in per-platform files (embed_<goos>_<goarch>.go)
// behind build tags. Each platform's build embeds only its own Node binary,
// keeping the final binary slim (~30 MB Node, not ~90 MB for all three).
package embed

// The blank import below is what enables the //go:embed directives. Even
// though our package is also named "embed", the import path is "embed"
// from the standard library; the underscore prevents binding a local name
// (which would collide with our own package identity).
import _ "embed"

// SidecarTarGz holds the gzipped tarball of the bgutil-sidecar/ folder
// (package.json, package-lock.json, src/, and production node_modules/).
// Generated by bgutil-sidecar/build.mjs. ~3.5 MB. Platform-agnostic JS.
//
//go:embed sidecar.tar.gz
var SidecarTarGz []byte

// Version is the cache-invalidation stamp baked into moombox.exe at build
// time. The sidecar manager compares this against the on-disk version.txt
// in the cache dir; mismatch triggers re-extraction. Format:
// "node@vX.Y.Z windows-amd64@<sha> linux-amd64@<sha> linux-arm64@<sha>".
//
//go:embed version.txt
var Version string
