//go:build windows && amd64

package embed

import _ "embed"

// EmbeddedNode holds the gzipped Windows x64 node.exe binary embedded
// into Moombox.exe. Generated by tools/fetch-node. ~34 MB at v24.20.0.
//
//go:embed node-windows-amd64.gz
var EmbeddedNode []byte
