//go:build linux && amd64

package embed

import _ "embed"

// EmbeddedNode holds the gzipped Linux x64 node binary embedded into
// the Linux x64 moombox build. Generated by tools/fetch-node. ~44 MB at v24.20.0.
//
//go:embed node-linux-amd64.gz
var EmbeddedNode []byte
