//go:build linux && arm64

package embed

import _ "embed"

// EmbeddedNode holds the gzipped Linux arm64 node binary embedded into
// the Linux arm64 moombox build. Generated by tools/fetch-node. ~43 MB at v24.20.0.
//
//go:embed node-linux-arm64.gz
var EmbeddedNode []byte
